var html = '<!doctype html>'
html = html + '<html>'
html = html + '<head>'
html = html + '<meta charset="utf-8">'
html = html + '<title>Your new GilbyIM account.</title>'
html = html + '<style type="text/css">'
html = html + '.body { width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; margin: 0; padding: 0; }'
html = html + 'a:link { color: #0073E7; text-decoration: none; }'
html = html + 'td { text-size-adjust: none; -webkit-text-size-adjust: none; }'
html = html + 'img { outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }'
html = html + 'a img { border: none; }'
html = html + 'a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }'
html = html + '/* Start Custom Styles */'
html = html + 'ul{ margin-top: 0; margin-bottom: 0; }'
html = html + 'li{ margin: 2.5px 0px 2.5px 0px; }'
html = html + 'li>span{ font-family: Calibri, Arial, Helvetica, sans-serif; font-size:14px; line-height:20px; color:#333333; }'
html = html + '.item-header{ font-family: Calibri, Arial, Helvetica, sans-serif; font-size:20px; font-weight:bold; line-height:26px; color:#ffffff; }'
html = html + '.item-header-cell{ padding: 10px 20px 10px 20px; border-bottom: solid; border-width: 1px; border-color: #cccccc; background-color: #000033; }'
html = html + '.item-content-cell{ padding: 20px 20px 20px 20px; border-bottom: none; border-width: 1px; border-color:#cccccc; background-color: #ffffff; }'
html = html + '.item-content{ font-family:Calibri, Arial, Helvetica, sans-serif; font-size:14px; line-height:20px; color:#333333; }'
html = html + '.item-image-cell{ border-bottom:none; border-width: 1px; border-color:#cccccc; align: center; }'
html = html + '.item-footer{ font-family: Calibri, Arial, Helvetica, sans-serif; font-size:14px; line-height:20px; color:#333333; }'
html = html + '.social-icon-cell{ -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding:0 10px 0px 0px; }'
html = html + '.social-icon{ width: 20px; height: 16px; border-width: 0px; border-style: solid; height: 16px; border: 0; }'
html = html + '.monotype{font-family: Courier; }'
html = html + '@media screen and (max-device-width: 480px) {'
html = html + '.mobilewidth { width: 100% !important; }'
html = html + '.mobilehide { display: none !important; }'
html = html + '.imageresize { -ms-interpolation-mode: bicubic; height: auto !important; width: 100% !important; }'
html = html + 'a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }'
html = html + '/* Start Custom Styles */'
html = html + '.item-header{ font-size:50px; line-height:67px; display:table; margin:0 auto; }'
html = html + '.item-content{ font-size:40px; line-height:53px; }'
html = html + '.item-footer{ font-size:40px; line-height:53px; }'
html = html + '.item-content-cell{ padding: 40px 40px 40px 40px; }'
html = html + '}'
html = html + '</style>'
html = html + '</head>'
html = html + '<body marginheight="0" marginwidth="0">'
html = html + '<table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr>'
html = html + '<td align="center">'
html = html + '<table class="mobilewidth" width="602" cellspacing="0" cellpadding="1" border="0"><tbody><tr><td bgcolor="#cccccc">'
html = html + '<table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody>'
html = html + '<!-- START: Company Logo -->'
html = html + '<tr style="">'
html = html + '<td style="padding:12px 0 10px 20px; border-bottom:solid; border-width:1px; border-color:#cccccc;" bgcolor="#ffffff" align="left"><a href="https://gilbyim.com/" target="_blank"><img alt="GilbyIM Logo" src="https://www.recordstransformation.co.uk/email/img/core/gilbyim-logo.png" width="222" height="33"></a></td>'
html = html + '</tr>'
html = html + '<!-- END: Company Logo -->'
html = html + '<!-- START: Banner -->'
html = html + '<tr>'
html = html + '<td style="border-bottom:solid; border-width:1px; border-color:#cccccc;" align="center" bgcolor="#FFFFFF"><img class="imageresize" src="https://www.recordstransformation.co.uk/email/img/core/banner.png" alt="GilbyIM: EDRMS as a Service" style="display: block; width: 600px; border-width: 0px; border-style: solid;" width="600" border="0"></td>'
html = html + '</tr>'
html = html + '<!-- END: Banner -->'
html = html + '<!-- START: Item 1 -->'
html = html + '<tr><td class="item-content-cell" align="left"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td align="left">'
html = html + '<table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr style=""><td valign="top" bgcolor="#ffffff" align="left">'
html = html + '<table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td align="left">'
html = html + '<span class="item-content">'
html = html + '<p>Hi Micky,</p>'
html = html + '<p>Welcome to <strong>GilbyIM - EDRMS as a Service</strong> . &nbsp;You are receiving this email because your organisation is using (or about to start using) GilbyIM as to manage its records, and we''ve been asked to set you up with a user account.</p>'
html = html + '<p>You can access the service at: </p>'
html = html + '<p style="margin-left: 35px"><a href="https://disney.gilbyim.com">https://disney.gilbyim.com</a></p>'
html = html + '<p>Your <strong>username</strong> is the email address we''ve been given for you: </p>'
html = html + '<p style="margin-left: 35px"><span class="monotype">michael.mouse@disney.com</span></p>'
html = html + '<p>We''ve assigned you a <strong>temporary password</strong>: </p>'
html = html + '<p style="margin-left: 35px"><span class="monotype">PD=sQ)u[_rR0TCk;F]DJ</span></p>'
html = html + '<p><strong>You should change your password to something more memorable as soon as you can.</strong></p>'
html = html + '<p>To change your password, visit: </p>'
html = html + '<p style="margin-left: 35px"><a href="https://authenticate.gilbyim.com/adfs/portal/updatepassword">https://authenticate.gilbyim.com/adfs/portal/updatepassword</a></p>'
html = html + '<p>The first time you login you''ll be asked to set up <strong>Two-Factor Authentication</strong>.  &nbsp;For more information on using Two-Factor Authentication with GilbyIM, see: </p>'
html = html + '<p style="margin-left: 35px"><a href="https://www.recordstransformation.co.uk/docs/customer-portal/gilbyim-faqs/accessing-gilbyim-using-two-factor-authentication.pdf" target="_blank">Accessing GilbyIM using Two-Factor Authentication</a></p>'
html = html + '<p>If you have any issues accessing the system, please do not hesitate to contact us:</p>'
html = html + '<p style="margin-left: 35px"><a href="mailto:contact@gilbyim.com?subject=I%20need%20help%20using%20GilbyIM%20for%20the%20first%20time.">contact@gilbyim.com</a></p>'
html = html + '<p>Finally, thank you for choosing GilbyIM. &nbsp;We are confident you won''t be disappointed.</p>'
html = html + '<p>Warmest regards,</p>'
html = html + '<p><strong>The GilbyIM Team</strong></p>'
html = html + '</span>'
html = html + '</td></tr></tbody></table>'
html = html + '</td>'
html = html + '</tr></tbody></table></td></tr>'
html = html + '<tr><td style="padding:0px 20px 0px 0px;" valign="bottom">&nbsp;</td></tr>'
html = html + '</tbody></table></td></tr>'
html = html + '<!-- END: Item 1 -->'
html = html + '<!-- START: Footer -->'
html = html + '<tr class="mobilehide"><td style="padding:20px 20px 10px 20px;" bgcolor="#ffffff"><table width="100%" cellspacing="0" cellpadding="0" border="0" align="left"><tbody><tr style=""><td align="left"><table align="left"><tbody><tr style="">'
html = html + '<td class="social-icon-cell" valign="middle" align="left"><a href="https://twitter.com/rt_gilbyim" target="_blank"><img alt="Titter Icon" src="https://www.recordstransformation.co.uk/email/img/core/icon_twitter.png" class="social-icon" style="width: 20px;" width="20" height="16" border="0"></a></td>'
html = html + '<td class="social-icon-cell" valign="middle" align="left"><a href="https://www.youtube.com/channel/UCl2C-ksVWfh0pcGNsEebxgA" target="_blank"><img alt="Youtube Icon" src="https://www.recordstransformation.co.uk/email/img/core/icon_youtube.png" class="social-icon" style="width: 13px;" width="13" height="16" border="0"></a></td>'
html = html + '<td class="social-icon-cell" valign="middle" align="left"><a href="https://www.linkedin.com/company/records-transformation" target="_blank"><img alt="LinkedIn Icon" src="https://www.recordstransformation.co.uk/email/img/core/icon_linkedin.png" class="social-icon" style="width: 17px;" width="17" height="16" border="0"></a></td>'
html = html + '</tr></tbody></table>'
html = html + '</td>'
html = html + '<td style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #888888; font-family:Calibri, Arial, Helvetica, sans-serif; font-size: 12px; width: 70%;" valign="middle" align="left">&nbsp;</td>'
html = html + '</tr>'
html = html + '<tr style=""><td align="left" colspan="6" style="font-family:Calibri, Arial, Helvetica, sans-serif; font-size: 12px; color:#888888; padding:10px 0;" valign="bottom"><p>For more information regarding GilbyIM Services Ltd''s privacy policy, please visit our <a href="https://www.recordstransformation.co.uk/privacy" target="_blank">privacy statement</a>.</p><br> © Copyright 2022 GilbyIM Services Ltd</td></tr>'
html = html + '</tbody></table></td></tr>'
html = html + '<!-- END: Footer -->'
html = html + '</tbody></table></td></tr>'
html = html + '</tbody></table></td></tr>'
html = html + '</tbody></table>'
html = html + '<span class="mobilehide" style="padding:0px 20px 0px 0px;" valign="bottom">&nbsp;</span>'
html = html + '<!-- Spacer after content table -->'
html = html + '</body>'
html = html + '</html>'

         

                                             


                                                
                                                

                                                   


                                    
